"""add markdown_content to uploaded_documents

Revision ID: 2f69676456df
Revises: 
Create Date: 2026-05-06 15:59:40.180467
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2f69676456df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_rag_chunks_embedding'), table_name='rag_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_rag_chunks_modality'), table_name='rag_chunks')
    op.drop_index(op.f('idx_rag_chunks_source'), table_name='rag_chunks')
    op.drop_index(op.f('idx_rag_chunks_tsv'), table_name='rag_chunks', postgresql_using='gin')
    op.drop_table('rag_chunks')
    op.add_column('uploaded_documents', sa.Column('markdown_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_documents', 'markdown_content')
    op.create_table('rag_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('heading', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('char_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('char_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modality', sa.TEXT(), server_default=sa.text("'text'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rag_chunks_pkey'))
    )
    op.create_index(op.f('idx_rag_chunks_tsv'), 'rag_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_rag_chunks_source'), 'rag_chunks', ['source_path'], unique=False)
    op.create_index(op.f('idx_rag_chunks_modality'), 'rag_chunks', ['modality'], unique=False)
    op.create_index(op.f('idx_rag_chunks_embedding'), 'rag_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
